# Generated by Django 5.1.4 on 2024-12-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_quizresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
