# Generated by Django 5.1.4 on 2024-12-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_question_quiz_quiz_answer_1_quiz_answer_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_correct',
            field=models.CharField(choices=[('answer_1', 'Answer 1'), ('answer_2', 'Answer 2'), ('answer_3', 'Answer 3'), ('answer_4', 'Answer 4')], default='answer_1', max_length=10),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.quiz')),
            ],
        ),
    ]
