# Generated by Django 5.1.4 on 2024-12-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_quiz_is_correct_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('answer_1', 'Answer 1'), ('answer_2', 'Answer 2'), ('answer_3', 'Answer 3'), ('answer_4', 'Answer 4')], default='answer_1', max_length=10),
        ),
    ]
