# Generated by Django 5.1.4 on 2024-12-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
